apiVersion: k3d.io/v1alpha4
kind: Simple
metadata:
  name: default
servers: 1
agents: 0
kubeAPI:
  host: "k3d.${DOMAIN}"
  hostIP: "0.0.0.0"
  hostPort: "6445"
image: rancher/k3s:v1.24.4-k3s1
subnet: "172.28.0.0/16"
# volumes:
#   - volume: /my/host/path:/path/in/node
#     nodeFilters:
#       - server:0
#       - agent:*
ports:
  - port: 80:80
    nodeFilters:
      - loadbalancer
  - port: 443:443
    nodeFilters:
      - loadbalancer
options:
  k3d:
    wait: true
    timeout: "60s"
    disableLoadbalancer: false
    disableImageVolume: false
    disableRollback: false
    loadbalancer:
      configOverrides:
        - settings.workerConnections=1024
  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: true